 
version: "3.3"

services:
    virtual-wallet:
        build: .
        environment:
            DB_ADDRESS: postgresql-db
            DB_USER: ${db_username}
            DB_PASSWORD: ${db_password}
            CRYPTO_API_KEY: ${crypto_api_key}
        depends_on:
            - postgresql-db
        ports:
            - 8080:8080
    postgresql-db:
        image: postgres:11.3-alpine
        ports:
            - 5432:5432
        environment:
          POSTGRES_USER: ${db_username}
          POSTGRES_PASSWORD: ${db_password}
        volumes:
            - /zzpj/postgresql:/var/lib/postgresql/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    docker-manager:
        image: portainer/portainer:1.20.2
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /nosql/portainer-data:/data
        ports:
            - 8090:9000
