 
version: "3.3"

services:
    virtual-wallet:
        build: .
        environment:
            db: postgresql-db
        depends_on:
            - postgresql-db
        ports:
            - 8080:8080
    postgresql-db:
        image: postgres:11.3-alpine
        volumes:
            - /zzpj/postgresql:/var/lib/postgresql/data

    docker-manager:
        image: portainer/portainer:1.20.2
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /nosql/portainer-data:/data
        ports:
            - 8090:9000
